# This workflow bumps the 'build' version based on the contents of the VERSION file.
# The VERSION file should be in the format of 'X.X.X--Y' - the 'Y' is incremented and
# pushed back to the VERSION file.
# For example, if the contents of VERSION were '2.1.1--1', after this runs the contents
# will be '2.1.1--2'.

name: CI

# Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        software_version=$(cat SOFTWARE_VERSION)
        version=$(cat VERSION)
        arrIN=(${version//--/ })
        new_base_version=$(echo ${arrIN[1]} + 1 | bc)
        echo "${software_version}--${new_base_version}" > VERSION
        git config --global user.name 'Kenneth Daily'
        git config --global user.email 'kdaily@users.noreply.github.com'
        git commit -am "Bump version to ${software_version}--${new_base_version}"
        git push
        echo "Bump version to ${software_version}--${new_base_version}"
